### ISSUE TITLE
Trying to load an XMM register hangs

### ISSUE THREAD

**Issue by shepmaster** [Tyilo/asm_repl#1]
I tried to run this, but it just hangs. :crying_cat_face: 

``` asm
mov xmm0, 0x0123456789abcdef
```

**Comment by tyilo** [comment]
You can't move an immediate value to an xmm0 register in x86 assembly. You would have to do something like:

```
mov rax, 0x0123456789abcdef
movq xmm0, rax
```

The reason that you don't get an error and it just hangs is that I was using radare's own x86 assembler, which basically doesn't have any error handling. I have switched to using nasm.

Anyways I probably would like to add a command to show and write to floating point registers

**Comment by tyilo** [comment]
I have tried to implement the command I talked about.

Usage:

```
> .show fpr-hex
fpr-hex toggled on
> .regs

 xmm0: 00000000000000000000000000000000
...
> .set xmm0 fedcba98765432100123456789abcdef
> .regs

 xmm0: FEDCBA98765432100123456789ABCDEF
 ...
```

Does this do what you want?

**Comment by shepmaster** [comment]
It certainly seems to, thanks!

**Comment by tyilo** [comment]
Cool!
