### ISSUE TITLE
Which registers will mess things up if modified? (Not an issue, but a question)

### ISSUE THREAD

**Issue by 04meta** [Tyilo/asm_repl#3]
I'm kind of too scared to do anything with this awesome "tool," if you can call it that (no offense!), because I'm thinking: Are RIP (if you could modify it directly), RSP, SS, and CS the only registers that will mess things up if I modify them (e.g. `mov rsp, rax` will obviously break it), and if not, what are the others? Also, are there any instructions (besides maybe `lock cmpxchg8b eax` and friends (the other registers, e.g. `lock cmpxchg8b ecx` etc.) of Pentium-F00F-bug fame) that will break things if I use them? #nestedparenthesesinprose

**Comment by tyilo** [comment]
This is really not a problem.
